### ISSUE TITLE
Unauthorized for url

### ISSUE THREAD

**Issue by sullrich84** [th0th/rancher-redeploy-workload#1]
Hi,

the action fails with the following exception:

```
Run th0th/rancher-redeploy-workload@v0.5
  env:
    JAVA_HOME_14.0.2_x64: /opt/hostedtoolcache/jdk/14.0.2/x64
    JAVA_HOME: /opt/hostedtoolcache/jdk/14.0.2/x64
    JAVA_HOME_14_0_2_X64: /opt/hostedtoolcache/jdk/14.0.2/x64
    RANCHER_URL: ***
    RANCHER_BEARER_TOKEN: ***
    RANCHER_PROJECT_ID: c-c4h5q:p-jmtml
    RANCHER_NAMESPACE: backend
    RANCHER_WORKLOAD: backend
/usr/bin/docker run --name aac2aac4fed6431ae9481182a22f595681e218_83994a --label aac2aa --workdir /github/workspace --rm -e JAVA_HOME_14.0.2_x64 -e JAVA_HOME -e JAVA_HOME_14_0_2_X64 -e RANCHER_URL -e RANCHER_BEARER_TOKEN -e RANCHER_PROJECT_ID -e RANCHER_NAMESPACE -e RANCHER_WORKLOAD -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/my-project/my-project":"/github/workspace" aac2aa:c4fed6431ae9481182a22f595681e218
Traceback (most recent call last):
  File "/rancher-redeploy-workload/redeploy_rancher_workload.py", line 61, in <module>
    response_get.raise_for_status()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: ***/v3/project/c-c4h5q:p-jmtml/workloads/deployment:backend:backend
```

I'm providing the `Bearer-Token` which I've create in rancher.

Any idea what could cause this?

**Comment by sullrich84** [comment]
You have to provide an unscoped `Bearer-Token`.

**Comment by th0th** [comment]
Hi @sullrich84, I am glad it worked :)
